### ISSUE TITLE
[FEAT]: Publisere artifakter til noe annet enn jitpack?

### ISSUE THREAD

**Issue by ahusby** [navikt/rapids-and-rivers#105]
### Description

Fordi https://github.com/jitpack/jitpack.io/issues/5337
Teamet mitt (Toi) er i trøbbel når jitpack-serveren er nede. Mange av våre apper bruker rapids-and-rivers og kan dermed ikke bygges og deployes, som betyr at vi ikke kan rette feil i prod uten videre hvis behovet skulle oppstå.

**Comment by havstein** [comment]
Jeg har prøvd å endre en av appene våre til å dra inn rapids-and-rivers fra kildekode i stedet for å laste ned fra et repo (jitpack/maven central eller lignende), men [det feiler](https://github.com/navikt/helse-sparkelapper/actions/runs/3759514522/jobs/6389185309) på noe avhengighetsgreier i test-scope. Det bygger fint lokalt.

https://github.com/navikt/helse-sparkelapper/compare/4a6cf77d96c4c7537e55e70f1b83b658b98b98b2^^..4a6cf77d96c4c7537e55e70f1b83b658b98b98b2

**Comment by chsko** [comment]
Kan evt. prøve å publisere til maven central/sonatype?
