### ISSUE TITLE
Om consumeren når max.poll.interval.ms dør lytteren uten videre seremoni

### ISSUE THREAD

**Issue by knutnyg** [navikt/rapids-and-rivers#21]
Vi har sett noen tilfeller av dette skje hvor pod'en står å ikke gjør noe. Her burde kanskje self-testen blitt flippa? (i tillegg til å stille på `max.poll.records` og `max.poll.interval.ms`)

```
{
  "@timestamp": "2021-02-18T12:08:11.994+01:00",
  "@version": "1",
  "message": "[Consumer clientId=consumer-sparkel-norg-ffcf44f7d-svkcx, groupId=sparkel-norg-v1] Member consumer-sparkel-norg-ffcf44f7d-svkcx-c1571ccd-3df7-4c67-98d4-6d247b30b4bd sending LeaveGroup request to coordinator a01apvl00146.adeo.no:8443 (id: 2147483645 rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.",
  "logger_name": "org.apache.kafka.clients.consumer.internals.AbstractCoordinator",
  "thread_name": "kafka-coordinator-heartbeat-thread | sparkel-norg-v1",
  "level": "INFO",
  "level_value": 20000
}
```

**Comment by junnae** [comment]
Denne er litt interessant. Har undersøkt loggene til spleis, at auto-skalering basert på ressursbruk kan slå inn og rebalansere hele gruppen. Men det så og ut som noen av konsumerne likevel klarte å rejoine, selvom de sendte en leave melding

**Comment by junnae** [comment]
Det kan hende david egentlig har fikset alt dette allerede.. Noe av koden er litt vanskelig å følge

**Comment by junnae** [comment]
Skyt meg hvis jeg tar feil, men mener: 389b5c316bc776f1ea94a4e95c42fb771581029c fikset denne

**Comment by junnae** [comment]
Har også sett i loggene at når spleis timer ut så har den fikset seg igjen.. Så jeg tenker vi evt kan reåpne denne hvis det blir et problem igjen (Burde vel da manifestere seg som et problem i offset lag)
