### ISSUE TITLE
La publish-funksjonen ta typen JsonMessage

### ISSUE THREAD

**Issue by ahusby** [navikt/rapids-and-rivers#29]
Det hadde vært kjekt hvis publish-funksjonen kunne tatt en parameter av typen JsonMessage. I dag tar den bare String. Det betyr at jeg må gjøre om min JsonMessage instans til en String før jeg kan publisere. Det er en helt triviell (?) operasjon som alltid må utføres, så det føles som det hadde vært på sin plass med en ekstra publish-metode i tillegg til dagens, som kan ta seg av dette for meg.

**Comment by havstein** [comment]
Er det noen fordel med å bruke `JsonMessage` over for eksempel `JsonNode` på _utgående_ meldinger? Utover at den ikke gir tilgang til innholdet på andre måter enn `toJson` - enkapsulering, typ.

**Comment by havstein** [comment]
Ah, kanskje hvis man ønsker å republisere en melding man har tatt inn i en River, ja 🤔
