### ISSUE TITLE
Dokumentasjon: Hvordan filtrere events fra rapid til river, i motsetning til validering?

### ISSUE THREAD

**Issue by ahusby** [navikt/rapids-and-rivers#30]
Mulig jeg ikke forstår ting riktig nå, men kanskje det kan være innspill til dokumentaskjon? Eksempelkoden på https://github.com/navikt/rapids-and-rivers#quick-start ser ut til å vise hvordan man validerer events som konsumeres fra en river. Det ser ut som at filtreringen i skrittet fra rapid til river har blitt gjort på forhånd. Skulle ønske dokumentasjonen/eksemplekoden fortalte hvordan filtreringen gjøres, ikke bare valideringen.

**Comment by ahusby** [comment]
Er det slik at "demand" brukes til filtrering så man får riktig event type (event name), mens "require" brukes til validering av events som vi vet er av riktig type?

**Comment by ahusby** [comment]
De fleste meldinger på en rapid vil ikke være interessante for en konsument og skal ignoreres. Hvorfor blir dette kalt "error" og "severe", når det er det mest normale som skjer?

**Comment by ahusby** [comment]
Kommer biblioteket kanskje med en antagelse som ikke gjelder for oss? For eksempel at en river er en egen ferdig filtrert topic, hvor alle meldinger i utgangspunktet skal behandles?

**Comment by androa** [comment]
I eksempelet så er det dette som setter opp Riveren:
```    init {
        River(rapidsConnection).apply {
            validate { it.demandValue("@event_name", "my_event") }
            validate { it.requireKey("a_required_key") }
            // nested objects can be chained using "."
            validate { it.requireValue("nested.key", "works_as_well") }
        }.register(this)
    }```
    
Altså, man tar en rapid og sier hvilke ting man vil sluse ut på en river som appen så behandler i `onPacket()`.

Forskjellen på `demand*` og `require*` går mest på hvor uventet det er. Vi har en konvensjon på at vi legger `@` foran "envelope"-felter, altså felter som er en del av hele rapiden, og ikke nødvendigvis innhold i pakka.

Typisk gjør vi `demand*` på ting vi *vet* skal være til stede og det mangler/oppfylles ikke det kravet kan vi stoppe parsingen umiddelbart.

`require*` brukes for felter vi forventer, men ønsker at det kastes feil om de mangler (i tilfelle noe(n) ukompatible endringer innføres).

`interestedIn` brukes hvor vi tillater `null`-verdier og har egne sjekker for det i selve appen.

**Comment by ahusby** [comment]
Du sier "Typisk gjør vi demand på ting vi VET skal være tilstede". Hva hvis det ligger events med key "@event_name" og value "my_event2" i tillegg til value "my_event"? Altså en annen eventtype. Og min river er bare interessert i å behandle events med event name "my_event2". Vi skal ignorere "my_event" events. I eksemeplet ser det ut som vi må håndtere det som en feilsituasjon i onSevere. Men dette vil jo være en normalsituasjon, ikke en feil?

**Comment by androa** [comment]
Du trenger ikke å håndtere noe i onSevere. Vi har så godt som ingen apper som implementerer den. I så fall så er det kun logging en liten periode. De fleste appene være har logging i onError.

**Comment by StefanEngelien-Nav** [comment]
Jeg snakket med team Rekrutteringsbistand om denne - her har de laget en "ekte" rapid etter Fred's beskrivelse, med forskjellige typer domenehendelser. Så forsøker de å bruke rapid-and-rivers til å lytte på og behandle meldinger om en spesifikk type domenehendelse, dvs at de bare er interessert i pakker der @event_name har en spesifikk verdi. Det bør jo da være naturlig og forventet at konsumenten støter på noen uinteressante pakker da, og ikke en feilsituasjon? Eller er det noe vi har misforstått?

**Comment by ahusby** [comment]
Jeg ser at det vil fungere å ikke gjøre noe i onSevere, men jeg fpr fremdeles ikke navnet "severe" til å gi mening. For dette use-caset, altså for å ignorere uinteressante meldinger. Det kunen ha eksistert en "onIgnore" handler for debuglogging underveis i utvikking. Med et tilhørende alternativ til requireKey og demandKey som kunne hete "ignoreUnlessKey" eller noe slikt. Jeg og @frodank skal se om vi klarer å finne tid til å lage en pullrequest med en slik utvidelse.

**Comment by havstein** [comment]
onSevere roper etter å få nytt navn. Betydningen er vel noe i retning av "onDemandedUnmet"?

Kunne gjerne hatt tydeligere navn enn require og demand også, men det er out of scope for dette issuet.

Jeg lurer på om demand-filtrene kommer mer til sin rett hvis de kommer etter en require? Da har man filtrert inn de meldingene man er ute etter (eks: `require("@event_name", "my_event2")`) og er mer interessert i hard fail hvis noe annet i meldingen er out of whack?

**Comment by ahusby** [comment]
@havstein Jeg opprettet egen issue for navn her: https://github.com/navikt/rapids-and-rivers/issues/31
