### ISSUE TITLE
Lesbarhet: Finnes det bedre navn for reject/deny og demand/require? 

### ISSUE THREAD

**Issue by ahusby** [navikt/rapids-and-rivers#31]
Navneparene `reject` vs. `deny` og `require` vs. `demand` fungerer ikke for å formidle forskjellen på dem. De er synonymer med bortimot helt lik betydning i mitt hode. Så det er litt slitsomt å prøve å huske hva de betyr. Går det an å finne navnpar som er mer ulike? I klassen JsonMessage.

**Comment by junnae** [comment]
Jeg er enig, semantikken er uklar og det er ikke intuitivt nok
