### ISSUE TITLE
Auto update using dependabot

### ISSUE THREAD

**Issue by audunstrand** [navikt/rapids-and-rivers#39]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

We should use dependabot to update R&R for all users.

**Comment by MikAoJk** [comment]
Is it this feature:
![image](https://user-images.githubusercontent.com/23274950/167395383-96ebfdbc-bf25-4629-b0cd-e60103560b1a.png)

If yes, then i have turned it on now

**Comment by audunstrand** [comment]
no, use depenedabot to update R&R for all users of the library

**Comment by MikAoJk** [comment]
isee
